library(ggvis)
library(ggplot2)
qplot(Petal.Width,Sepal.Width, data = iris, color = Species, shape = (Petal.Length>1.6), size = (Sepal.Length>5))
qplot(mpg,data=mtcars, geom = "density",fill=gear,alpha = 0.5)
qplot(mpg,data=mtcars, geom = "histogram",fill=gear, color = "black", alpha = 0.5,bins = 40)
qplot(hp, mpg, data=mtcars, color=am, facets=gear~cyl, size=I(3))
qplot(gear, mpg, data=mtcars,geom = c("jitter", "point"))
ggplot(mtcars, aes(mpg,hp,color = gear))+geom_point()
ggplot(mtcars, aes(gear,cyl,fill = gear))+geom_bar(stat = "identity")
ggplot(mtcars, aes(gear)) + geom_bar(stat="count")
ggplot(mtcars, aes(mpg,hp,color = gear))+geom_point(size = 3) + geom_line(color = "black",linetype = "dashed")+expand_limits(y=0)
ggplot(mtcars, aes(mpg,hp,color = gear,group=gear))+geom_point(size = 3) + geom_line(color = "black",linetype = "dashed")
mtcars %>% ggvis(~wt) %>% layer_densities(adjust = input_slider(0.1, 2, value = 1, step = 0.1, label = "Bandwidth adjustment"),kernel = input_select(c("Gaussian" = "gaussian", "Epanechnikov" = "epanechnikov",  "Rectangular" = "rectangular","Triangular" = "triangular", "Biweight" ="biweight", "Cosine" = "cosine", "Optcosine" = "optcosine"),label = "Kernel"))
mtcars %>% ggvis(~wt, ~mpg) %>% layer_points() %>% add_tooltip(function(df) c("wt - ", df$wt, " mpg - ", df$mpg))
